{% set name = "sphinx-toggleprompt" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 59c726ecf3f0bb48be77f96b823ce6bcf4ed15ef1e0d6d85bed781b72d9347df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2 <3.1
    - python >=3.6
    - sphinx >=1.8

test:
  imports:
    - sphinx_toggleprompt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jurasofish/sphinx-toggleprompt
  summary: Add a python prompt toggle to each code cell.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Moisan
