{% set name = "sphinx-toggleprompt" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-toggleprompt-{{ version }}.tar.gz
  sha256: b3f4f015da3d8d45218830ef6df3b7b7daf0db535b6e7bfeda989fab61731d75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2 <3.1
    - python >=3.6
    - sphinx >=1.8

test:
  imports:
    - sphinx_toggleprompt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jurasofish/sphinx-toggleprompt
  summary: Add a python prompt toggle to each code cell.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - Moisan
